[tool.ruff]
target-version = "py312"
line-length = 88
exclude = ["venv", "migrations", "__pycache__", ".git"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C4"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
